"""empty message

Revision ID: 0457f2e281b4
Revises: 
Create Date: 2022-02-17 04:36:14.575839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0457f2e281b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anuncio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=1000), nullable=False),
    sa.Column('detalle', sa.String(length=1500), nullable=False),
    sa.Column('autor', sa.String(length=50), nullable=False),
    sa.Column('nivel', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )
    op.create_table('apoderado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('genero', sa.String(length=80), nullable=False),
    sa.Column('nacionalidad', sa.String(length=80), nullable=False),
    sa.Column('ocupacion', sa.String(length=80), nullable=False),
    sa.Column('maxNivelEducativo', sa.String(length=80), nullable=False),
    sa.Column('fechanac', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('nombre', sa.String(length=500), nullable=False),
    sa.Column('categoria', sa.String(length=120), nullable=False),
    sa.Column('nivel', sa.String(length=120), nullable=False),
    sa.Column('propietario', sa.String(length=120), nullable=False),
    sa.Column('visible', sa.Boolean(create_constraint=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('permisos', sa.Boolean(), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('direccion', sa.String(length=15), nullable=False),
    sa.Column('rol', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('direccion'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rol'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('ninio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('fechanac', sa.Date(), nullable=False),
    sa.Column('nivelEducativo', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=False),
    sa.Column('nee', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['apoderado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destinatario', sa.String(length=15), nullable=False),
    sa.Column('cuerpo', sa.String(length=1500), nullable=False),
    sa.Column('funcionarioId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['funcionarioId'], ['funcionario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destinatario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sms')
    op.drop_table('ninio')
    op.drop_table('funcionario')
    op.drop_table('documento')
    op.drop_table('apoderado')
    op.drop_table('anuncio')
    # ### end Alembic commands ###
