"""empty message

Revision ID: 9fc6d58ab288
Revises: 
Create Date: 2022-02-17 02:38:57.578960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc6d58ab288'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anuncio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=1000), nullable=False),
    sa.Column('detalle', sa.String(length=1500), nullable=False),
    sa.Column('autor', sa.String(length=50), nullable=False),
    sa.Column('nivel', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('titulo')
    )
    op.create_table('documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('nombre', sa.String(length=500), nullable=False),
    sa.Column('categoria', sa.String(length=120), nullable=False),
    sa.Column('nivel', sa.String(length=120), nullable=False),
    sa.Column('propietario', sa.String(length=120), nullable=False),
    sa.Column('visible', sa.Boolean(create_constraint=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documento')
    op.drop_table('anuncio')
    # ### end Alembic commands ###
